Serialize error stack and loglevel field
spreaker/pkg-node-logger pull request #3
Opened 2019-09-05 13:19 UTC by teorossi82

In this PR we want to add 2 functions to our logger:
- errors serialization
- add loglevel field to each logs

To be able to develop them I've proxied the `Pino logger` and I've intercepted the `write` method; in this way I had the possibility to insert these customizations before call the original method.
I've added some comments and updated the `README` to explain the changes better.

2019-09-05 13:32 UTC, lele85 requested changes
I think you forgot the parsing of the error stack :)

2019-09-05 13:36 UTC, teorossi82 commented
> I think you forgot the parsing of the error stack :)

Thanks @lele85, I'll add it right now so we can log also `error_file` and `error_line`.

2019-09-06 08:34 UTC, lele85 approved these changes
Great job @teorossi82! this is gonna bring joy to our logger users (ourselves) :)

2019-09-06 10:56 UTC, teorossi82 commented
@lele85 as you suggested me I have mapped the `loglevel` with our standard and I also add a check to log the `loglevel` field only for `Application loggers`.

2019-09-09 12:08 UTC, lele85 requested changes
Just one more thing to check :)

2019-09-10 12:46 UTC, lele85 approved these changes
Looks good now! Great job.

2019-09-11 14:47 UTC, merged